"""empty message

Revision ID: 675f9ae44c6b
Revises: fc3ec5c2b13a
Create Date: 2021-01-01 04:03:09.819949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675f9ae44c6b'
down_revision = 'fc3ec5c2b13a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uuid', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_column('users', 'uuid')
    # ### end Alembic commands ###
